import Head from 'next/head'
import Image from "next/image";
import axios from 'axios'
import {useState} from 'react';
import {BeSearch} from 'react-icons/bs';

export default function Home() {
    const [city,setCity] = useState('');
    const [weather,setWeather] = useState({});
    const [loading,setLoading] = useState(false);


    const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

    const fetchWeather = (e) => {
        e.preventDefault()
        setLoading(true)
        axios.get(url).then((response) => {
            setWeather(response.data)
            console.log(response.data)
        })
        setCity('')
        setLoading(false)
    }

  return (
    <div>
      <Head>
        <title>Weather -  Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Image src='https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=775&q=80'
    layout='fill'/>
    </div>
  )
}
